# Generated by Django 4.2.7 on 2025-04-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_Sub',
            new_name='is_sub',
        ),
    ]
