# Generated by Django 4.2.7 on 2025-04-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='adrress_receiver',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='mobile',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='note_receiver',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_receiver',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
