# Generated by Django 4.2.7 on 2025-04-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_address_shippingaddress_adrress_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='name_receiver',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
